// Ultra field snapshot from Guandata BI metadata: 49 row fields and 26 metric fields.
window.YejiPzShuju = {
rowFieldKeys: [
"PSDJsLbUyxFsFWMYBbnyQstm",
"nebZXyfTkXXEVuOZOzmokaMJ",
"wrwhWXLeUwhBWFhDZLVGXhSN",
"KgSJkfeCHnsgTuPDWfvbkxVA",
"VIQBHtqVjElTkfjQWlxHBehE",
"xrrNIpvllWUonPupwLQJTQbr",
"AoCWJTGYHIMAlVjHdmQDAxvA",
"NfiGMgLTzdvZDxlovIiJsOOu",
"OyYtFDOisBITxSKjVjWSubeP",
"pUGjhtVZnCrOcuDutxUPfGrb",
"PdemEhVGWWVuuAFpgHsMAKLl",
"nshtppqevKuYHxJZFpOHCEym",
"tmCLNLQCDhwqTJwZRfnESkEE",
"asTCfdSzyWvGkoEldnoneeQm",
"yIZeIhasdqpJddkkxaqYHLfi",
"ONIGZmMTyCNQNkDASmjEuzaQ",
"RocAwvPJuPeVvbTknMGlhWlA",
"rUiitlKECAtJKaTgaUjKokxK",
"VTEYlTfYYEUuobkupyuNGVBc",
"UCpSNMIJctBYpajnWHuLuoup",
"WwapcrXKYORANIceFyqtAlpc",
"VtbxAQTRBDreUYJVKktMXgFE",
"NjdJllrkvnlMJQzPIaWjGtMV",
"TdYzgkqhELBaxWcuexMJNAKb",
"DdUfbaRkSgOyamSAtCUhdwCk",
"VvQxwkapDEmDRGopJnDSCURa",
"kpBvjBmOrPLRVOnrFluUjmWW",
"vtrzVOkZbHUHuhoEpdEEtyNJ",
"huloDALOhQpsuBQtdOuJWrVH",
"AULUENbiGegNPXdpxgurtahG",
"HYhQxLBKupmzcwJoBitbIRaH",
"DswHsZkXRxmIBTfEpcGGrXsT",
"VlKWJbltPoDprCUbPQapqzTG",
"RKIbRTTMjCivBldiwxqLAokv",
"nGGMtosIiODYyXwlKlNftgeE",
"lriZOfaOtYYPktbgZWLCDvNP",
"TylsahITlBCxeHSEoFaROkdY",
"yhGbbSMTPLpoGMpIWPdwYgYZ",
"IkDvQfIXZoxVSzQKDmsXfpDh",
"AMtIkRGiIhpAguETEvXCMeeM",
"YUiopSFKLOyeNGyvfWidnMEP",
"yXxqRdBaSIfcekUJLxZNAxCf",
"zJVeJWOsvQCsGHCmSTVWjUBP",
"lUpjpZsVQHCPxWantspYZgbV",
"rulmFqaRAokhofvclHYKdTGN",
"XfJrYnPBcAhLLkDWtvpbPoOD",
"ZpayISLWNEumIwUciTwXFHOa",
"brlTzLUaxadIxredTkotriFq"
],
rowFieldLabels: {
PSDJsLbUyxFsFWMYBbnyQstm: "出库月份（月）",
wrwhWXLeUwhBWFhDZLVGXhSN: "支付日期（月）",
PdemEhVGWWVuuAFpgHsMAKLl: "药品id",
huloDALOhQpsuBQtdOuJWrVH: "区",
AMtIkRGiIhpAguETEvXCMeeM: "运单号"
},
metricFieldKeys: [
"VGfVfarkNvRsSwAMIsYSqMSA",
"WEqpSMNKbyJQVSDiTTwjWJaf",
"mMMEKOJLXPyjlXjmfgAvltOr",
"zwsliJYMNdBRYyeqQWWoxJDE",
"pDdTnkYVcZdkIfPDmINydkJU",
"luGxYuozpExWlYkCXQXVjLji",
"nRkRweEApEZBxNIAJijgHbpL",
"OpGrNIZXYravRaucxUYolsxa",
"tbFUpGYDfQgCNOAGOGOycEPr",
"wPGfHWZqVaPDXtKAeCaxhXTc",
"yujkvdbZlDahssKWseSZNelh",
"TugIiphQmoZPiIjMyHTWFzoh",
"qPiEndoCGZChAlvDXDtFTGVN",
"RdsWrXUFddlBMbDbjlKNhbFa",
"dCXrTSwxSFgjuudIGvkrFpbL",
"VxljwkzPcfXfZBZXqJwwqHbB",
"KDPMilUbvhnnHNlxfDTUbpXt",
"OIarCNLfRiLjFWUrCaXVZAfg",
"YmZUVTlZsQnmqxtGRrPIyWdF",
"NeQtrSldSbFoGeUThoaGzANr",
"TLhdnxmnTcISGHJtGaPULWbN",
"oSgYeaAMILyOjXVEeANjDiju",
"XcfyBmbUftdlEaCMHYeVySqX",
"VPdHsUUxAqqOMSUhYhZBpqoj",
"qrqyQsbChrvmJwvShumuNqTc",
"ufXgOfzeQaHfvypADiagxKAG"
],
metricFieldLabels: {
TLhdnxmnTcISGHJtGaPULWbN: "客户数",
oSgYeaAMILyOjXVEeANjDiju: "商品编码去重计数",
XcfyBmbUftdlEaCMHYeVySqX: "spuid去重计数",
VPdHsUUxAqqOMSUhYhZBpqoj: "出库日期去重计数",
qrqyQsbChrvmJwvShumuNqTc: "支付日期去重计数"
},
rowFields: [
{key:"OyYtFDOisBITxSKjVjWSubeP",fdId:"e2cf19230839641debd5516c",name:"ERP商品编码",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"tmCLNLQCDhwqTJwZRfnESkEE",fdId:"jdd2df11bcea94082bab3dfa",name:"商品名称",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"DdUfbaRkSgOyamSAtCUhdwCk",fdId:"i5767918168f841918af08ec",name:"省内外",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"VlKWJbltPoDprCUbPQapqzTG",fdId:"v03b35fb5461345fd8a900be",name:"客户类型",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"nGGMtosIiODYyXwlKlNftgeE",fdId:"pc31754e7fd7a40739f30521",name:"活动类型",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"WwapcrXKYORANIceFyqtAlpc",fdId:"j15ca66a3dde4417fac8af6e",name:"厂牌",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"xrrNIpvllWUonPupwLQJTQbr",fdId:"p757056ca0f984bf39e128c6",name:"子公司id",fdType:"LONG",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"PdemEhVGWWVuuAFpgHsMAKLl",fdId:"r6a9b98caaff54edfb9ae4d3",name:"药师帮ID",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"nshtppqevKuYHxJZFpOHCEym",fdId:"v913152f850b44c0ca563192",name:"spuid",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"NjdJllrkvnlMJQzPIaWjGtMV",fdId:"je5c9188fb5714cd09a0b42f",name:"运营负责人",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"VvQxwkapDEmDRGopJnDSCURa",fdId:"c1ebaa172cc47477d80820ad",name:"环数标签",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"VtbxAQTRBDreUYJVKktMXgFE",fdId:"ifca606d9e98e4450920afea",name:"品种负责人",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"lriZOfaOtYYPktbgZWLCDvNP",fdId:"wb6d6af5af1484268af905d2",name:"单据类型",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"TdYzgkqhELBaxWcuexMJNAKb",fdId:"sf0cca238e787449cad15b17",name:"业务类型",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"asTCfdSzyWvGkoEldnoneeQm",fdId:"ma4ad10caafdb4342b9e5f5b",name:"商品规格",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"PSDJsLbUyxFsFWMYBbnyQstm",fdId:"u9c320c996de34c62a6c8a59_month",name:"月",fdType:"SUB_DATE",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:"",parentFdName:"出库月份",granularity:"MONTH"},
{key:"UCpSNMIJctBYpajnWHuLuoup",fdId:"o68030b095bc74362b0838d0",name:"通用名",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"pUGjhtVZnCrOcuDutxUPfGrb",fdId:"s63da26b1d9c640259217497",name:"乐药编码",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"yIZeIhasdqpJddkkxaqYHLfi",fdId:"p97492d8c64864cc49db76d7",name:"商品类别",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"ONIGZmMTyCNQNkDASmjEuzaQ",fdId:"c5afbe9cdeb3e4d44ac6c4f3",name:"处方分类",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"RocAwvPJuPeVvbTknMGlhWlA",fdId:"g665985680ddb4becbae2e46",name:"采购大类",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"rUiitlKECAtJKaTgaUjKokxK",fdId:"mc8391daa76a844588bf0198",name:"采购亚类",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"VTEYlTfYYEUuobkupyuNGVBc",fdId:"xb08ccd71cf2a4961bc4ae6c",name:"采购小类",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"rVXHgIYPNAQKYeiIRRiGUJhm",fdId:"d7f27a52688be4f1ebd14e4b",name:"省内排名",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"TylsahITlBCxeHSEoFaROkdY",fdId:"jf0f485704d9546f0a06c154",name:"批次",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"yhGbbSMTPLpoGMpIWPdwYgYZ",fdId:"t8b132044e40943bc8c714e8",name:"批号",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"YUiopSFKLOyeNGyvfWidnMEP",fdId:"f8bac224742f84cc88d6f260",name:"出库单号",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"zJVeJWOsvQCsGHCmSTVWjUBP",fdId:"p762160baf41342a6ae07f72",name:"药师帮单号",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"RKIbRTTMjCivBldiwxqLAokv",fdId:"hdfe2943a3bc943a2a70e026",name:"活动id",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"HYhQxLBKupmzcwJoBitbIRaH",fdId:"j0599925ad3024ff9bcadfdb",name:"客户编码",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"DswHsZkXRxmIBTfEpcGGrXsT",fdId:"i1929f755ea9a4ad2942eb94",name:"客户名称",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"nebZXyfTkXXEVuOZOzmokaMJ",fdId:"t4115ca5bb1574cb39287216",name:"出库日期",fdType:"DATE",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"AoCWJTGYHIMAlVjHdmQDAxvA",fdId:"od5ddc53f7c1f43cdbfbad4d",name:"子公司名称",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"NfiGMgLTzdvZDxlovIiJsOOu",fdId:"u1934cedb5f94443a8d33ae3",name:"仓库名称",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"kpBvjBmOrPLRVOnrFluUjmWW",fdId:"p3cac7f687a804497b74b98b",name:"省份",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"vtrzVOkZbHUHuhoEpdEEtyNJ",fdId:"becf6177142c2477fa93f47a",name:"城市",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"AULUENbiGegNPXdpxgurtahG",fdId:"e5f8c7f2d4dee47139e62902",name:"药店id",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"KgSJkfeCHnsgTuPDWfvbkxVA",fdId:"h8052c3c2934345ac89563ab",name:"支付日期",fdType:"DATE",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"wrwhWXLeUwhBWFhDZLVGXhSN",fdId:"h8052c3c2934345ac89563ab_month",name:"月",fdType:"SUB_DATE",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:"",parentFdName:"支付日期",granularity:"MONTH"},
{key:"huloDALOhQpsuBQtdOuJWrVH",fdId:"xdd37bafd66dd4aa6962d12d",name:"区new",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"VIQBHtqVjElTkfjQWlxHBehE",fdId:"kf4b0a843f64d484086e91a1",name:"星期几（支付日期）",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"rulmFqaRAokhofvclHYKdTGN",fdId:"d1985e29e8b23417cb49ebbd",name:"是否5W",fdType:"INT",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"lUpjpZsVQHCPxWantspYZgbV",fdId:"h904257877f094e3caa1cd17",name:"是否3K",fdType:"INT",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"ZpayISLWNEumIwUciTwXFHOa",fdId:"qe7ee34400ec64713a829fef",name:"l标签",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"XfJrYnPBcAhLLkDWtvpbPoOD",fdId:"w439d007433d745a6a1f3b72",name:"是否3K5W",fdType:"DOUBLE",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"yXxqRdBaSIfcekUJLxZNAxCf",fdId:"u7dbde1e10e1c409a8154c48",name:"销售开票单号",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"AMtIkRGiIhpAguETEvXCMeeM",fdId:"e3cd3d2c2a2b94b19bdf9b21",name:"快递单号",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"brlTzLUaxadIxredTkotriFq",fdId:"kf6e72effaae7461b90fdd90",name:"自动化运营标签",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""},
{key:"IkDvQfIXZoxVSzQKDmsXfpDh",fdId:"a0870ebde255e47e6a43b289",name:"快递公司",fdType:"STRING",metaType:"DIM",isAggregated:false,calculationType:"normal",level:"dataset",annotation:""}
],
metricFields: [
{key:"nRkRweEApEZBxNIAJijgHbpL",fdId:"cb81635b7a3d54f838627583",name:"不含税p4毛利额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"mMMEKOJLXPyjlXjmfgAvltOr",fdId:"n573b564d00ca419bbec9bbd",name:"销售数量",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"luGxYuozpExWlYkCXQXVjLji",fdId:"q6c08a5957234441bb19d1ab",name:"含税p4毛利额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"zwsliJYMNdBRYyeqQWWoxJDE",fdId:"kd9cc9b350a6e485c8003ec0",name:"含税p1毛利额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"pDdTnkYVcZdkIfPDmINydkJU",fdId:"r1ff2dd59e5bb49a7897a24b",name:"不含税p1毛利额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"OpGrNIZXYravRaucxUYolsxa",fdId:"b6a8d0fbcaf50486ba930e32",name:"含税实收毛利额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"tbFUpGYDfQgCNOAGOGOycEPr",fdId:"lf5d533599ba74cd8946e7f7",name:"不含税实收毛利额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"wPGfHWZqVaPDXtKAeCaxhXTc",fdId:"va2632995c49346e5aa246de",name:"不含税仓库人工费",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"yujkvdbZlDahssKWseSZNelh",fdId:"q5fc6287a3a794ec586dae58",name:"含税配送费",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"TugIiphQmoZPiIjMyHTWFzoh",fdId:"na0cfa42d3261427683379f9",name:"不含税配送费",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"qPiEndoCGZChAlvDXDtFTGVN",fdId:"t9d07f5009c6a4527bdf0b98",name:"不含税平台费",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"RdsWrXUFddlBMbDbjlKNhbFa",fdId:"obaa2da21d1744e4a9d4765f",name:"优惠金额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"VGfVfarkNvRsSwAMIsYSqMSA",fdId:"j0e16b46f641d4dfa9dd7a3c",name:"含税金额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"WEqpSMNKbyJQVSDiTTwjWJaf",fdId:"mc2f8b25eae18461288dd87b",name:"不含税金额",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM",alias:"不含税金额"},
{key:"YmZUVTlZsQnmqxtGRrPIyWdF",fdId:"t088430c70d1647efbefcdcb",name:"不含税平台费率",fdType:"DOUBLE",metaType:"METRIC",isAggregated:true,calculationType:"aggregation",baseFdType:"DOUBLE",level:"dataset",annotation:"",formula:"sum([不含税平台费])/sum([不含税金额])"},
{key:"dCXrTSwxSFgjuudIGvkrFpbL",fdId:"c0ba10fa8ddb44775aaa305e",name:"不含税边际利润",fdType:"DOUBLE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DOUBLE",level:"dataset",annotation:"",aggrType:"SUM"},
{key:"NeQtrSldSbFoGeUThoaGzANr",fdId:"f1f06f56a7015406a821e343",name:"不含税边际利润率",fdType:"DOUBLE",metaType:"METRIC",isAggregated:true,calculationType:"aggregation",baseFdType:"DOUBLE",level:"dataset",annotation:"",formula:"sum([不含税边际利润])/sum([不含税金额])"},
{key:"VxljwkzPcfXfZBZXqJwwqHbB",fdId:"wf551b20e6bba4a03a214005",name:"不含税P4毛利率",fdType:"DOUBLE",metaType:"METRIC",isAggregated:true,calculationType:"aggregation",baseFdType:"DOUBLE",level:"dataset",annotation:"",formula:"sum([不含税p4毛利额])/sum([不含税金额])"},
{key:"OIarCNLfRiLjFWUrCaXVZAfg",fdId:"nde764f4ca9fa498f8d0aafe",name:"不含税配送费率",fdType:"DOUBLE",metaType:"METRIC",isAggregated:true,calculationType:"aggregation",baseFdType:"DOUBLE",level:"dataset",annotation:"",formula:"sum([不含税配送费])/sum([不含税金额])"},
{key:"KDPMilUbvhnnHNlxfDTUbpXt",fdId:"mb6f3f3f8785f4b2dab1acaa",name:"不含税人工费率",fdType:"DOUBLE",metaType:"METRIC",isAggregated:true,calculationType:"aggregation",baseFdType:"DOUBLE",level:"dataset",annotation:"",formula:"sum([不含税仓库人工费])/sum([不含税金额])"},
{key:"TLhdnxmnTcISGHJtGaPULWbN",fdId:"i1929f755ea9a4ad2942eb94",name:"客户名称",fdType:"STRING",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"STRING",level:"dataset",annotation:"",aggrType:"CNT_DISTINCT",alias:"客户数"},
{key:"oSgYeaAMILyOjXVEeANjDiju",fdId:"e2cf19230839641debd5516c",name:"ERP商品编码",fdType:"STRING",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"STRING",level:"dataset",annotation:"",aggrType:"CNT_DISTINCT",alias:"商品编码去重计数"},
{key:"VPdHsUUxAqqOMSUhYhZBpqoj",fdId:"t4115ca5bb1574cb39287216",name:"出库日期",fdType:"DATE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DATE",level:"dataset",annotation:"",aggrType:"CNT_DISTINCT",alias:"出库日期去重计数"},
{key:"qrqyQsbChrvmJwvShumuNqTc",fdId:"h8052c3c2934345ac89563ab",name:"支付日期",fdType:"DATE",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"DATE",level:"dataset",annotation:"",aggrType:"CNT_DISTINCT",alias:"支付日期去重计数"},
{key:"XcfyBmbUftdlEaCMHYeVySqX",fdId:"v913152f850b44c0ca563192",name:"spuid",fdType:"STRING",metaType:"METRIC",isAggregated:false,calculationType:"normal",baseFdType:"STRING",level:"dataset",annotation:"",aggrType:"CNT_DISTINCT",alias:"spuid去重计数"},
{key:"ufXgOfzeQaHfvypADiagxKAG",fdId:"jf41259a9fcc049e1af636a4",name:"条目单价",fdType:"DOUBLE",metaType:"METRIC",isAggregated:true,calculationType:"aggregation",baseFdType:"DOUBLE",level:"dataset",annotation:"",formula:"sum([不含税金额])/count(case when [单据类型] = '销售出库单' then 1 end)"}
]
};
